source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

# Ruby on Rails
gem 'rails', '~> 5.1.5'

# Task runner
gem 'foreman'

# Use Puma as the app server
gem 'puma', '~> 3.7'

# Redis driver
gem 'redis'

# Redis object-hash mapping
gem 'ohm'
gem 'ohm-contrib'

# Date parser
gem 'chronic'

# A simple Redis-based session store for Rails
# https://github.com/roidrage/redis-session-store
gem 'redis-session-store'

# Embed the V8 JavaScript interpreter into Ruby
gem "therubyrhino"

# Ruby wrapper for UglifyJS JavaScript compressor
gem 'uglifier'

# Use SASS for stylesheets
gem 'sass-rails'

# Templating engine for HTML
gem 'haml'

# Material Design Icons for rails
gem 'material_design_icons'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem 'jbuilder', '~> 2.5'

group :development do
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end
