[workspace]
# members = ["space/starfox"]

[workspace.package]
keywords = ["web4", "cloud", "ai-powered", "os"]
license = "LGPL"

[profile.release]
codegen-units = 1
opt-level = "z"
lto = true
panic = "abort"
overflow-checks = true
