[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.libs-build]
command = "cargo"
args = ["build", "--target", "wasm32-unknown-unknown", "--release", "--lib"]
dependencies = ["clean"]

[tasks.voyager-client-dev-build]
workspace = false
cwd = "./service/voyager/client/web/"
command = "dioxus"
args = ["build", "--platform", "web"]
dependencies = ["dioxus-cli-setup"]

[tasks.voyager-client-prod-build]
workspace = false
cwd = "./service/voyager/client/web/"
command = "dioxus"
args = ["build", "--platform", "web", "--release"]
dependencies = ["dioxus-cli-setup"]

[tasks.voyager-client-dev-serve]
workspace = false
cwd = "./service/voyager/client/web/"
command = "dioxus"
args = ["serve", "--platform", "web", "--hot-reload", "--port", "1337"]
dependencies = ["dioxus-cli-setup"]

[tasks.dev]
workspace = false
dependencies = ["voyager-client-dev-serve"]
