[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.dioxus-cli-install]
command = "cargo"
args = ["install", "--git", "https://github.com/mrxiaozhuox/dioxus-cli"]

[tasks.dioxus-cli-plugin-system-init]
command = "dioxus"
args = ["plugin", "init"]
dependencies = ["dioxus-cli-install"]

[tasks.dioxus-cli-plugin-tailwind-install]
command = "dioxus"
args = [
	"plugin",
	"add",
	"--git",
	"https://github.com/DioxusPluginCommunity/tailwind-plugin",
]
dependencies = ["dioxus-cli-plugin-system-init"]

[tasks.dioxus-cli-setup]
command = "echo"
args = ["Installing plugins..."]
dependencies = ["dioxus-cli-plugin-tailwind-install"]

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.libs-build]
command = "cargo"
args = ["build", "--target", "wasm32-unknown-unknown", "--release", "--lib"]
dependencies = ["clean"]

[tasks.starfox-desktop-dev-build]
workspace = false
cwd = "./spaces/starfox-desktop/"
command = "dioxus"
args = ["build", "--platform", "web"]
dependencies = ["dioxus-cli-setup"]

[tasks.starfox-desktop-prod-build]
workspace = false
cwd = "./spaces/starfox-desktop/"
command = "dioxus"
args = ["build", "--platform", "web", "--release"]
dependencies = ["dioxus-cli-setup"]

[tasks.starfox-desktop-dev-serve]
workspace = false
cwd = "./spaces/starfox-desktop/"
command = "dioxus"
args = ["serve", "--platform", "web", "--hot-reload", "--port", "1337"]
dependencies = ["dioxus-cli-setup"]

[tasks.akaia-demo-dev-build]
workspace = false
cwd = "./spaces/akaia-demo/"
command = "dioxus"
args = ["build", "--platform", "web"]
dependencies = ["dioxus-cli-setup"]

[tasks.akaia-demo-prod-build]
workspace = false
cwd = "./spaces/akaia-demo/"
command = "dioxus"
args = ["build", "--platform", "web", "--release"]
dependencies = ["dioxus-cli-setup"]

[tasks.akaia-demo-dev-serve]
workspace = false
cwd = "./spaces/akaia-demo/"
command = "dioxus"
args = ["serve", "--platform", "web", "--hot-reload", "--port", "1337"]
dependencies = ["dioxus-cli-setup"]

[tasks.dev]
workspace = false
dependencies = ["starfox-desktop-dev-serve"]
