# fstrm_capture
# Autogenerated from man page /usr/share/man/man1/fstrm_capture.1.gz
complete -c fstrm_capture -s w -l write -d 'Write data to the file filename'
complete -c fstrm_capture -s t -l type -d 'Specify the content-type to receive from the socket and write to the output f…'
complete -c fstrm_capture -s u -l unix -d 'Listen on the Unix domain socket socket-path to receive Frame Streams data'
complete -c fstrm_capture -s a -l tcp -d 'Listen for TCP connections on address IP to receive Frame Streams data'
complete -c fstrm_capture -s p -l port -d 'If -a is given, listen on TCP port port to receive Frame Streams data'
complete -c fstrm_capture -s c -l maxconns -d 'Allow at most max-conns concurrent connections'
complete -c fstrm_capture -s b -l buffersize -d 'Set read buffer size to buffersize bytes'
complete -c fstrm_capture -s s -l split -d 'Reopen output file every interval seconds'
complete -c fstrm_capture -l gmtime -d 'Process the --write filename through strftime() with the current time in GMT'
complete -c fstrm_capture -l localtime -d 'Process the --write filename through strftime() with the current time in the …'
complete -c fstrm_capture -s d -s d -l debug -l debug -d 'Increase debugging level'

