# fstrm_replay
# Autogenerated from man page /usr/share/man/man1/fstrm_replay.1.gz
complete -c fstrm_replay -s t -l type -d 'Specify the content-type to read from files and send to the Frame Streams soc…'
complete -c fstrm_replay -s r -l read -d 'Read data from file.  Multiple files can be given with multiple -r options'
complete -c fstrm_replay -s u -l unix -d 'Connect to Unix domain socket-path to write Frame Streams data'
complete -c fstrm_replay -s a -l tcp -d 'Connect to TCP address IP to write Frame Streams data'
complete -c fstrm_replay -s p -l port -d 'If -a is given, use TCP port port to write Frame Streams data'

